//
// Created by gabriel on 25/05/19.
//

#ifndef T2FS_ERROR_H
#define T2FS_ERROR_H

// EXCEPTIONS ARE NEGATIVE NUMBERS
#define EXCEPTION -1
#define EMPTY_LINE_EXCEPTION -2
#define NULL_POINTER_EXCEPTION -3
#define MALLOC_ERROR_EXCEPTION -7
#define NOT_A_PATH_EXCEPTION -8
#define RELATIVE_PATH_NOT_SUPPORTED_EXCEPTION -9
#define FAILED_TO_READ_SECTOR -10
#define FAILED_TO_WRITE_SECTOR -11
#define INVALID_SIZE_FOR_FILE_NAME -12
#define HASH_TABLE_FULL -13
#define INDEX_OUT_OF_RANGE -14
#define KEY_ALREADY_PRESENT -15
#define MAX_OPENED_FILES_REACHED -16
#define DIRECTORY_NOT_OPENED -17

#define FILE_NOT_FOUND -404
#define BLOCK_IS_FREE -401
#define COULD_NOT_REACH_DESIRED_BLOCK -777
#define UNABLE_TO_WRITE_IN_FILE -402

// -------------------------------
#define SUCCESS_CODE 0
#define ERROR_CODE -100
#define FULL_BLOCKS -999
// -------------------------------

#define LAST_BLOCK 988
#define DEBUG 0
#define WROTE_EVERYTHING 123

#endif //T2FS_ERROR_H
